### ISSUE TITLE
Make the debug:queues output more concise

### ISSUE THREAD

**Issue by rocketage** [inviqa/spryker-debug#24]
OOTB Spryker implements a fair amount of queues, and projects can then extend them further. As each queue has a corresponding error queue the list of queues can be more rows that will fit in a standard console. 

Generally you are mainly interested in a few key things:
- Which queues have messages?
- How many messages are in total?

I suggest we add a '--all' flag to provide the current behavior and have the default remove any queues with no message activity from the output. Adding a total message count would also be a nice 'omg-how-long-is-this-going-to-take' indicator.

**Comment by dantleech** [comment]
What about a `--not-empty` flag?

I think having all queues by default is less surprising (than OMG WHERE ALL ALL MY QUEUES).

Is total messages really indicative of how long it wil take? Workers are independent and some queues take longer than others to process.

**Comment by rocketage** [comment]
A friendly message saying something like 'No queues containing messages found, run --all to show all empty queues' would avoid a missing queues panic, but maybe my use-case for this command is different to others. I just want to see any queues with messages, and have an idea of the total.
To keep current behavior `--not-empty` would work if it has a good shortcut like `-e` or `--active` `-a`, etc, and the total is more a nice to have than an important feature.
